# Generated by Django 4.1.6 on 2023-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_remove_userprofile_id_userprofile_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
