# Generated by Django 4.1.6 on 2023-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
