# Generated by Django 4.1.6 on 2023-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_user_otp_created_user_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
